version: '3.7'
services:
  php:
    container_name: app_php
    image: app-dev
    env_file:
      - ./.docker/app/.env
    build:
      target: dev
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - .:/php/src/initx/php-docker-skeleton

#  nginx:
#    container_name: magecore_nginx
#    image: magecore-nginx
#    build:
#      context: .
#      dockerfile: .docker/nginx/Dockerfile
#    ports:
#      - "80:80"
#    links:
#      - php
#    volumes:
#      - ./logs/nginx:/var/log/nginx:cached
#      - .:/php/src/initx/php-docker-skeleton:cached
