version: '3.7'
services:
  app:
    container_name: app_php
    image: app-dev
    env_file:
      - .docker/shared_env
    build:
      target: dev
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - .:/php/src/initx/php-docker-skeleton

  nginx:
    container_name: app_nginx
    image: app-nginx
    env_file:
      - .docker/shared_env
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8080:80"
    links:
      - app
    volumes:
      - .docker/logs/nginx:/var/log/nginx
      - .:/php/src/initx/php-docker-skeleton
