on:
  push:
    branches:
      - master

name: Build Images

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build App image
        id: build-app-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t app:$IMAGE_TAG \
            --target=prod \
            --file .docker/app/Dockerfile .

      - name: Build Nginx image
        id: build-nginx-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t nginx:$IMAGE_TAG \
            --file .docker/nginx/Dockerfile .
